channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - r-base=4.2
  - r-ggplot2
  - r-stringr
  - r-ggpubr
  - r-diptest
  - r-gridextra
  - python=3.7
  - pip:
    - statistics
    - operator
    - random
    - numpy
    - copy
    - sys
    - os
